[build]
command = """
  git submodule update --init --recursive &&
  hugo --minify &&
"""

[build.environment]
GO_VERSION = "1.21.3"
HUGO_VERSION = "0.120.4"

[context.production]
  environment = { BASE_URL = "https://kluctl.io/" }

[[redirects]]
  from = "/docs/reference/*"
  to = "/docs/kluctl/reference/:splat"
[[redirects]]
  from = "/docs/concepts"
  to = "/docs/kluctl/concepts"
[[redirects]]
  from = "/docs/get-started"
  to = "/docs/kluctl/get-started"
[[redirects]]
  from = "/docs/history"
  to = "/docs/kluctl/history"
[[redirects]]
  from = "/docs/installation"
  to = "/docs/kluctl/installation"
[[redirects]]
  from = "/docs/philosophy"
  to = "/docs/kluctl/philosophy"

[[redirects]]
  from = "/docs/flux/*"
  to = "/docs/gitops"

[[redirects]]
  from = "/docs/kluctl/concepts"
  to = "/docs/kluctl"
[[redirects]]
  from = "/docs/kluctl/history"
  to = "/docs/kluctl"
[[redirects]]
  from = "/docs/kluctl/philosophy"
  to = "/docs/kluctl"

[[redirects]]
  from = "/docs/kluctl/reference/gitops/*"
  to = "/docs/gitops/:splat"
[[redirects]]
  from = "/docs/kluctl/reference/*"
  to = "/docs/kluctl/:splat"
